### ISSUE TITLE
Create a request for compatibility in the JSONP

### ISSUE THREAD

**Issue by Thihup** [leadpony/joy#4]
As per the README, this project is JSONP compatible, so it would be great to create a request for compatibility in the JSONP project, like this one: https://github.com/eclipse-ee4j/jsonp/issues/257

If it is approved, it should be listed here: https://jakarta.ee/specifications/jsonp/2.0/

**Comment by Thihup** [comment]
I've run the TCK and looks like there are some failures:
```
     [echo] com/sun/ts/tests/jsonp/api/jsonobjecttests/Client.java#jsonObjectExceptionTests_from_standalone...................Failed..Test.case.throws.exception:.jsonObjectExceptionTests.Failed
     [echo] com/sun/ts/tests/jsonp/api/jsonparserfactorytests/Client.java#jsonParserFactoryExceptionTest_from_standalone......Failed..Test.case.throws.exception:.jsonParserFactoryExceptionTest.Failed
     [echo] com/sun/ts/tests/jsonp/api/patchtests/PatchTests.java#jsonPatchAddTest_from_standalone............................Failed..Test.case.throws.exception:.The.value.must.have.the.same.type.as.the.target.
     [echo] com/sun/ts/tests/jsonp/api/patchtests/PatchTests.java#jsonPatchMoveTest_from_standalone...........................Failed..Test.case.throws.exception:.RFC.6902.move.operation.failed:.MOVE./wife.object:.[{"op":"move","path":"/wife","from":"/wife"}].operation.for./wife.failed.on.JSON.{}.value.MOVE./married.object:.[{"op":"move","path":"/married","from":"/married"}].operation.for./married.failed.on.JSON.{"name":"John.Smith"}.value.MOVE./age.object:.[{"op":"move","path":"/age","from":"/age"}].operation.for./age.failed.on.JSON.{"name":"John.Smith","child":{"name":"John.Connor","age":6}}.value.MOVE./5.array:.[{"op":"move","path":"/5","from":"/5"}].operation.for./5.failed.on.JSON.[false,true,true,false,true].value                                                                                                                             
     [echo] com/sun/ts/tests/jsonp/api/pointertests/PointerTests.java#jsonPointerAddOperationTest_from_standalone.............Failed..Test.case.throws.exception:.The.value.must.have.the.same.type.as.the.target.

     [echo] Completed running 187 tests.
     [echo] Number of Tests Passed = 182
     [echo] Number of Tests Failed = 5
     [echo] Number of Tests with Errors = 0
```

Should I open issues to address them?

(I can help set up the TCK if you will)

**Comment by leadpony** [comment]
@Thihup 

Yes, please open issues.
I need your help for setting up the TCK.

**Comment by leadpony** [comment]
@Thihup 
Now this library passes all of 187 tests in the TCK with your great help. :smile:
So what should I do next?

**Comment by Thihup** [comment]
@leadpony Good job fixing the issues ;)
Now I guess there is only one requirement before opening an issue in the jsonp repo:
You should put the result in a public place, I don't know if you would like to commit the result in this repo or add it to a site.

It should be similar to this: https://eclipse-ee4j.github.io/jsonp/tck/TCK-Results.html

And then you can open the issue like this one: https://github.com/eclipse-ee4j/jsonp/issues/257

**Comment by leadpony** [comment]
@Thihup 
Thank you for your advice.
I will try it immediately after releasing the next version.

**Comment by Thihup** [comment]
I guess now it is ready!
There is some discussion about where the Jakarta team will publish the results, but now it is possible to claim that this implementation is compatible :)
Thanks

**Comment by leadpony** [comment]
@Thihup 
Much appreciated.
Without your help, I could not reach here.
