### ISSUE TITLE
Root Pointer should replace existing object 

### ISSUE THREAD

**Issue by Thihup** [leadpony/joy#7]
Test: https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jsonp/api/pointertests/PointerAdd.java#L649

It uses a root pointer to replace the existing object with the array.
It is failing because it throws `JsonException: The value must have the same type as the target`

**Comment by Thihup** [comment]
Test: https://github.com/eclipse-ee4j/jakartaee-tck/blob/4d7d240306059693082475fc935edf54eb93572b/src/com/sun/ts/tests/jsonp/api/patchtests/PatchOperationAdd.java#L513

Fails with the same issue

**Comment by leadpony** [comment]
@Thihup 
I expect you are right, but the Javadoc of JSON-P API states:

> If the reference is the target (empty JSON Pointer string), the specified value, which must be the same type as specified target, is returned.
https://www.javadoc.io/static/jakarta.json/jakarta.json-api/2.0.0/jakarta.json/jakarta/json/JsonPointer.html#add(T,jakarta.json.JsonValue)

Therefore my implementation throws a JsonException. 
OK, I will modify it.

**Comment by Thihup** [comment]
Please don't take my word for granted 😉 
If you think there is some test that is not correct, you can open a _challenge_ to the JSONP repo.
However, there are some places where the Javadoc is not fully clear, and the TCK provides more information.

(We're writing a Servlet container, [Piranha](https://piranha.cloud), so we have the same issues to pass the Servlet TCK 😂 )
